db:
    mongoUri: "mongodb://user:user@ds119736.mlab.com:19736/si1718-avp-dissertations"
    #mongoUri: "mongodb://test:test@ds149535.mlab.com:49535/si1718-avp-sandbox"
auth0:
    jwksUri: "https://si1718-avp.eu.auth0.com/.well-known/jwks.json"
    #audience: "https://si1718-avp-dissertations-alvarovp27.c9users.io/"
    audience: "https://si1718-avp-dissertations.herokuapp.com/"
    issuer: "https://si1718-avp.eu.auth0.com/"
    